//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globalization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Globalization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ChoiceIsRequired {
            get {
                return ResourceManager.GetString("ChoiceIsRequired", resourceCulture);
            }
        }
        
        public static string VotesIsRequired {
            get {
                return ResourceManager.GetString("VotesIsRequired", resourceCulture);
            }
        }
        
        public static string QuestionIsRequired {
            get {
                return ResourceManager.GetString("QuestionIsRequired", resourceCulture);
            }
        }
        
        public static string ImageIsRequired {
            get {
                return ResourceManager.GetString("ImageIsRequired", resourceCulture);
            }
        }
        
        public static string ThumbIsRequired {
            get {
                return ResourceManager.GetString("ThumbIsRequired", resourceCulture);
            }
        }
        
        public static string ChoicesIsRequired {
            get {
                return ResourceManager.GetString("ChoicesIsRequired", resourceCulture);
            }
        }
        
        public static string InternalServerErrorTryAgainLater {
            get {
                return ResourceManager.GetString("InternalServerErrorTryAgainLater", resourceCulture);
            }
        }
    }
}
